version: "3.9"  # optional since v1.27.0

services:
  backend:
    build: ./backend
    volumes:
      - .:/code
  backend_migrate:
    extends:
      service: backend
    command: python backend/django_backend/manage.py migrate
  backend_run:
    extends:
      service: backend
    command: python backend/django_backend/manage.py runserver 0.0.0.0:${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
  frontend:
    build: 
      context: ./frontend
      target: build
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - exclude_node_modules_frontend:/app/node_modules
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    command: npm run serve -- --port ${CLIENT_PORT} --host 0.0.0.0
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
  webrtc_backend:
    build: ./webrtc_backend
    volumes:
      - ./webrtc_backend:/app
    command: npm run start
    ports:
      - ${WEBRTC_HTTP_PORT}:${WEBRTC_HTTP_PORT}
      - ${WEBRTC_HTTPS_PORT}:${WEBRTC_HTTPS_PORT}

volumes:
  exclude_node_modules_frontend: