# Generated by Django 4.0.1 on 2022-01-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_ver_email_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ver_email_code',
            field=models.CharField(db_index=True, default='35763286789', max_length=48, unique=True),
        ),
    ]
