# Generated by Django 4.0.1 on 2022-01-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_conferencing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conference',
            name='url',
            field=models.CharField(default='o4jrgk4', max_length=13),
        ),
        migrations.AlterField(
            model_name='members',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
