# Generated by Django 4.0.1 on 2022-01-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_conferencing', '0002_alter_conference_id_alter_conference_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='url',
            field=models.CharField(default='8vcz0l0r', max_length=13),
        ),
    ]
